import { Provider, Service } from "./types";

// ── Providers ──────────────────────────────────────────────────────

export const providers: Provider[] = [
  {
    id: "aquacare-kw",
    name: "AquaCare Kuwait",
    category: "pool",
    description:
      "Kuwait's most trusted swimming pool maintenance company since 2012. We specialize in residential and commercial pool care, offering weekly maintenance plans, emergency repairs, and full renovation services. Our team of certified technicians ensures your pool stays crystal clear all year round.",
    descriptionAr:
      "أكثر شركات صيانة أحواض السباحة موثوقية في الكويت منذ 2012. نتخصص في العناية بالأحواض السكنية والتجارية، ونقدم خطط صيانة أسبوعية وإصلاحات طارئة وخدمات تجديد كاملة. فريقنا من الفنيين المعتمدين يضمن بقاء حوضك نقياً طوال العام.",
    rating: 4.8,
    reviewCount: 124,
    location: "Salwa, Block 10",
    locationAr: "السالوة، قطعة 10",
    governorate: "Hawalli",
    basePrice: 25,
    isVerified: true,
    whatsappNumber: "96599001234",
    image: "",
    yearsInBusiness: 14,
    completedJobs: 2340,
  },
  {
    id: "crystal-pools",
    name: "Crystal Pool Services",
    category: "pool",
    description:
      "Premium pool repair and installation experts serving all of Kuwait. From pump replacements to complete pool builds, Crystal Pool delivers unmatched quality. We use only imported, high-grade materials and provide a 2-year warranty on all repair work.",
    descriptionAr:
      "خبراء إصلاح وتركيب أحواض السباحة الفاخرة في جميع أنحاء الكويت. من استبدال المضخات إلى بناء الأحواض الكاملة، كريستال بول تقدم جودة لا مثيل لها. نستخدم فقط مواد مستوردة عالية الجودة ونوفر ضمان لمدة سنتين على جميع أعمال الإصلاح.",
    rating: 4.5,
    reviewCount: 89,
    location: "Mishref, Block 6",
    locationAr: "مشرف، قطعة 6",
    governorate: "Hawalli",
    basePrice: 35,
    isVerified: true,
    whatsappNumber: "96599005678",
    image: "",
    yearsInBusiness: 8,
    completedJobs: 1450,
  },
  {
    id: "gulf-fountain",
    name: "Gulf Fountain Masters",
    category: "fountain",
    description:
      "Specialists in decorative fountain design, installation, and maintenance. We transform outdoor spaces with stunning water features for villas, hotels, and commercial properties. Our portfolio includes over 200 custom fountain projects across the GCC.",
    descriptionAr:
      "متخصصون في تصميم وتركيب وصيانة النوافير الزخرفية. نحول المساحات الخارجية بمعالم مائية مذهلة للفلل والفنادق والعقارات التجارية. محفظتنا تشمل أكثر من 200 مشروع نافورة مخصص في دول الخليج.",
    rating: 4.9,
    reviewCount: 67,
    location: "Al-Zahra, Block 3",
    locationAr: "الزهراء، قطعة 3",
    governorate: "Hawalli",
    basePrice: 40,
    isVerified: true,
    whatsappNumber: "96599009012",
    image: "",
    yearsInBusiness: 11,
    completedJobs: 890,
  },
  {
    id: "blue-oasis",
    name: "Blue Oasis Co.",
    category: "pool",
    description:
      "Affordable and reliable pool cleaning for Kuwaiti families. We believe every home deserves a clean pool without the premium price tag. Our flexible weekly and bi-weekly plans are designed for busy homeowners who want hassle-free pool care.",
    descriptionAr:
      "تنظيف أحواض سباحة موثوق وبأسعار معقولة للعائلات الكويتية. نؤمن بأن كل منزل يستحق حوض سباحة نظيف بدون أسعار مبالغ فيها. خططنا المرنة الأسبوعية ونصف الأسبوعية مصممة لأصحاب المنازل المشغولين.",
    rating: 4.2,
    reviewCount: 43,
    location: "Jahra, Block 1",
    locationAr: "الجهراء، قطعة 1",
    governorate: "Jahra",
    basePrice: 15,
    isVerified: false,
    whatsappNumber: "96599003456",
    image: "",
    yearsInBusiness: 3,
    completedJobs: 520,
  },
  {
    id: "salmiya-experts",
    name: "Al-Salmiya Pool Experts",
    category: "pool",
    description:
      "Full-service pool company with a dedicated team for water testing, chemical balancing, and advanced filtration system maintenance. We serve residential compounds and private villas across the Hawalli governorate with same-day service availability.",
    descriptionAr:
      "شركة خدمات أحواض سباحة متكاملة مع فريق متخصص لفحص المياه وموازنة الكيماويات وصيانة أنظمة الترشيح المتقدمة. نخدم المجمعات السكنية والفلل الخاصة في محافظة حولي مع توفر خدمة في نفس اليوم.",
    rating: 4.7,
    reviewCount: 98,
    location: "Salmiya, Block 12",
    locationAr: "السالمية، قطعة 12",
    governorate: "Hawalli",
    basePrice: 30,
    isVerified: true,
    whatsappNumber: "96599007890",
    image: "",
    yearsInBusiness: 6,
    completedJobs: 1780,
  },
  {
    id: "desert-springs",
    name: "Desert Springs Fountains",
    category: "fountain",
    description:
      "From elegant garden water walls to grand commercial fountain displays, Desert Springs brings your vision to life. Our engineering team handles complex multi-jet fountain systems, LED-lit water features, and smart-controlled installations with remote monitoring.",
    descriptionAr:
      "من جدران المياه الأنيقة في الحدائق إلى عروض النوافير التجارية الكبرى، ديزرت سبرينغز تحول رؤيتك إلى واقع. فريقنا الهندسي يتولى أنظمة النوافير متعددة النفاثات وإضاءة LED والتركيبات الذكية مع المراقبة عن بُعد.",
    rating: 4.6,
    reviewCount: 55,
    location: "Ahmadi, Block 7",
    locationAr: "الأحمدي، قطعة 7",
    governorate: "Ahmadi",
    basePrice: 50,
    isVerified: true,
    whatsappNumber: "96599004321",
    image: "",
    yearsInBusiness: 9,
    completedJobs: 640,
  },
  // ── Fish Pool Providers ──────────────────────────────────────────
  {
    id: "kw-aquarium",
    name: "Kuwait Aquarium Pro",
    category: "fish",
    description:
      "Kuwait's premier fish pool and aquarium specialists. We design, build, and maintain stunning indoor and outdoor fish pools for homes, offices, and commercial spaces. From koi ponds to tropical aquariums, we bring aquatic beauty to your space.",
    descriptionAr:
      "المتخصصون الأوائل في أحواض الأسماك والأحياء المائية في الكويت. نصمم ونبني ونصون أحواض أسماك داخلية وخارجية مذهلة للمنازل والمكاتب والمساحات التجارية. من أحواض الكوي إلى الأحواض الاستوائية، نجلب جمال المياه إلى مساحتك.",
    rating: 4.7,
    reviewCount: 72,
    location: "Salmiya, Block 8",
    locationAr: "السالمية، قطعة 8",
    governorate: "Hawalli",
    basePrice: 35,
    isVerified: true,
    whatsappNumber: "96599006789",
    image: "",
    yearsInBusiness: 7,
    completedJobs: 680,
  },
  {
    id: "reef-masters",
    name: "Reef Masters Kuwait",
    category: "fish",
    description:
      "Specialized in marine and reef aquarium setups. We offer complete fish pool solutions including custom tank design, filtration systems, live coral and fish supply, and ongoing maintenance programs. Serving all of Kuwait with delivery and installation.",
    descriptionAr:
      "متخصصون في إعداد أحواض الشعاب المرجانية والأسماك البحرية. نقدم حلول أحواض أسماك متكاملة تشمل تصميم الأحواض المخصصة وأنظمة الترشيح وتوريد الشعاب الحية والأسماك وبرامج صيانة مستمرة. نخدم جميع أنحاء الكويت مع التوصيل والتركيب.",
    rating: 4.5,
    reviewCount: 48,
    location: "Farwaniya, Block 4",
    locationAr: "الفروانية، قطعة 4",
    governorate: "Farwaniya",
    basePrice: 25,
    isVerified: true,
    whatsappNumber: "96599008765",
    image: "",
    yearsInBusiness: 5,
    completedJobs: 420,
  },
];

// ── Pool Services (from Blank 4.xlsx) ─────────────────────────────

const poolServices: Service[] = [
  // ── Construction ────────────────────────────────────────────────
  {
    id: "svc-1",
    providerId: "crystal-pools",
    name: "Basic Skimmer (5x3m)",
    nameAr: "حوض تصفية أساسي (5×3م)",
    price: 2500,
    priceDisplay: "2,500 KWD",
    priceDisplayAr: "2,500 د.ك",
    description: "Standard In-Ground concrete pool.",
    descriptionAr: "حوض خرساني قياسي داخل الأرض.",
    serviceCategory: "construction",
  },
  {
    id: "svc-2",
    providerId: "crystal-pools",
    name: "Premium Custom / Infinity",
    nameAr: "مخصص فاخر / إنفينيتي",
    price: 11000,
    priceDisplay: "11,000 KWD",
    priceDisplayAr: "11,000 د.ك",
    description: "Custom high-end build.",
    descriptionAr: "بناء فاخر مخصص.",
    serviceCategory: "construction",
  },
  {
    id: "svc-3",
    providerId: "salmiya-experts",
    name: "Fiberglass Shell",
    nameAr: "قالب فايبرجلاس",
    price: null,
    priceDisplay: "Varies",
    priceDisplayAr: "يختلف",
    description: "Installation included.",
    descriptionAr: "التركيب مشمول.",
    serviceCategory: "construction",
  },
  {
    id: "svc-4",
    providerId: "salmiya-experts",
    name: "Above-Ground",
    nameAr: "فوق الأرض",
    price: null,
    priceDisplay: "Varies",
    priceDisplayAr: "يختلف",
    description: "Steel frame or portable.",
    descriptionAr: "هيكل معدني أو متنقل.",
    serviceCategory: "construction",
  },
  {
    id: "svc-5",
    providerId: "crystal-pools",
    name: "Design & Build",
    nameAr: "تصميم وبناء",
    price: null,
    priceDisplay: "Case-by-case",
    priceDisplayAr: "حسب الحالة",
    description: "Includes structure, waterproofing, pumps.",
    descriptionAr: "يشمل الهيكل، العزل المائي، المضخات.",
    serviceCategory: "construction",
  },

  // ── Maintenance ─────────────────────────────────────────────────
  {
    id: "svc-6",
    providerId: "aquacare-kw",
    name: "Annual Contract (AMC)",
    nameAr: "عقد سنوي (صيانة)",
    price: 170,
    priceDisplay: "170 – 259 KWD",
    priceDisplayAr: "170 – 259 د.ك",
    description: "Scheduled weekly/bi-weekly visits.",
    descriptionAr: "زيارات مجدولة أسبوعية/نصف أسبوعية.",
    serviceCategory: "maintenance",
  },
  {
    id: "svc-7",
    providerId: "aquacare-kw",
    name: "Single Cleaning Visit",
    nameAr: "زيارة تنظيف واحدة",
    price: 20,
    priceDisplay: "20 – 50 KWD",
    priceDisplayAr: "20 – 50 د.ك",
    description: "Skimming and chemical adjustment.",
    descriptionAr: "كشط وتعديل كيماوي.",
    serviceCategory: "maintenance",
  },
  {
    id: "svc-8",
    providerId: "blue-oasis",
    name: "Annual Contract (AMC)",
    nameAr: "عقد سنوي (صيانة)",
    price: 170,
    priceDisplay: "170 – 259 KWD",
    priceDisplayAr: "170 – 259 د.ك",
    description: "Scheduled weekly/bi-weekly visits.",
    descriptionAr: "زيارات مجدولة أسبوعية/نصف أسبوعية.",
    serviceCategory: "maintenance",
  },
  {
    id: "svc-9",
    providerId: "blue-oasis",
    name: "Single Cleaning Visit",
    nameAr: "زيارة تنظيف واحدة",
    price: 20,
    priceDisplay: "20 – 50 KWD",
    priceDisplayAr: "20 – 50 د.ك",
    description: "Skimming and chemical adjustment.",
    descriptionAr: "كشط وتعديل كيماوي.",
    serviceCategory: "maintenance",
  },

  // ── Equipment ───────────────────────────────────────────────────
  {
    id: "svc-10",
    providerId: "salmiya-experts",
    name: "Circulation Pump (1.5 HP)",
    nameAr: "مضخة دوران (1.5 حصان)",
    price: 140,
    priceDisplay: "140 KWD",
    priceDisplayAr: "140 د.ك",
    description: "Standard pool pump.",
    descriptionAr: "مضخة حوض قياسية.",
    serviceCategory: "equipment",
  },
  {
    id: "svc-11",
    providerId: "salmiya-experts",
    name: "Circulation Pump (3.0 HP)",
    nameAr: "مضخة دوران (3.0 حصان)",
    price: 215,
    priceDisplay: "215 KWD",
    priceDisplayAr: "215 د.ك",
    description: "Heavy duty pump.",
    descriptionAr: "مضخة عالية القدرة.",
    serviceCategory: "equipment",
  },
  {
    id: "svc-12",
    providerId: "crystal-pools",
    name: "Water Chiller",
    nameAr: "مبرد مياه",
    price: 920,
    priceDisplay: "920 KWD",
    priceDisplayAr: "920 د.ك",
    description: "Heating and Cooling system.",
    descriptionAr: "نظام تدفئة وتبريد.",
    serviceCategory: "equipment",
  },
  {
    id: "svc-13",
    providerId: "salmiya-experts",
    name: "Salt Chlorinator",
    nameAr: "معقم ملحي",
    price: null,
    priceDisplay: "Varies",
    priceDisplayAr: "يختلف",
    description: "Hayward brand typical.",
    descriptionAr: "ماركة Hayward عادةً.",
    serviceCategory: "equipment",
  },

  // ── Supplies ────────────────────────────────────────────────────
  {
    id: "svc-14",
    providerId: "aquacare-kw",
    name: "Chlorine Granules (5kg)",
    nameAr: "حبيبات كلور (5 كجم)",
    price: 12,
    priceDisplay: "12 KWD",
    priceDisplayAr: "12 د.ك",
    description: "Sanitation granules.",
    descriptionAr: "حبيبات تعقيم.",
    serviceCategory: "supplies",
  },
  {
    id: "svc-15",
    providerId: "aquacare-kw",
    name: "pH Decreaser (2.5lb)",
    nameAr: "مخفض pH (2.5 رطل)",
    price: 3,
    priceDisplay: "3 KWD",
    priceDisplayAr: "3 د.ك",
    description: "Powder chemical.",
    descriptionAr: "مسحوق كيماوي.",
    serviceCategory: "supplies",
  },
  {
    id: "svc-16",
    providerId: "blue-oasis",
    name: "Chlorine Granules (5kg)",
    nameAr: "حبيبات كلور (5 كجم)",
    price: 12,
    priceDisplay: "12 KWD",
    priceDisplayAr: "12 د.ك",
    description: "Sanitation granules.",
    descriptionAr: "حبيبات تعقيم.",
    serviceCategory: "supplies",
  },
  {
    id: "svc-17",
    providerId: "blue-oasis",
    name: "pH Decreaser (2.5lb)",
    nameAr: "مخفض pH (2.5 رطل)",
    price: 3,
    priceDisplay: "3 KWD",
    priceDisplayAr: "3 د.ك",
    description: "Powder chemical.",
    descriptionAr: "مسحوق كيماوي.",
    serviceCategory: "supplies",
  },

  // ── Repairs ─────────────────────────────────────────────────────
  {
    id: "svc-18",
    providerId: "aquacare-kw",
    name: "Repairs & Renovation",
    nameAr: "إصلاحات وتجديد",
    price: null,
    priceDisplay: "Quote basis",
    priceDisplayAr: "بناءً على التقييم",
    description: "Leak fixing and acid washing.",
    descriptionAr: "إصلاح التسريبات والغسيل الحمضي.",
    serviceCategory: "repairs",
  },
  {
    id: "svc-19",
    providerId: "crystal-pools",
    name: "Repairs & Renovation",
    nameAr: "إصلاحات وتجديد",
    price: null,
    priceDisplay: "Quote basis",
    priceDisplayAr: "بناءً على التقييم",
    description: "Leak fixing and acid washing.",
    descriptionAr: "إصلاح التسريبات والغسيل الحمضي.",
    serviceCategory: "repairs",
  },
];

// ── Fountain Services (from Blank 6.xlsx) ─────────────────────────

const fountainServices: Service[] = [
  // Gulf Fountain Masters
  {
    id: "fsvc-1",
    providerId: "gulf-fountain",
    name: "New Pool Construction",
    nameAr: "إنشاء حوض سباحة جديد",
    price: 5000,
    priceDisplay: "5,000 – 15,000+ KWD",
    priceDisplayAr: "5,000 – 15,000+ د.ك",
    description: "Design and build of concrete or residential/commercial pools (waterproofing, pumps, lighting, finishes). One-time / Custom Quote.",
    descriptionAr: "تصميم وبناء أحواض خرسانية سكنية/تجارية (عزل مائي، مضخات، إضاءة، تشطيبات). لمرة واحدة / عرض سعر مخصص.",
    serviceCategory: "construction",
  },
  {
    id: "fsvc-2",
    providerId: "gulf-fountain",
    name: "Annual Maintenance Contract",
    nameAr: "عقد صيانة سنوي",
    price: 170,
    priceDisplay: "170 – 250+ KWD",
    priceDisplayAr: "170 – 250+ د.ك",
    description: "Regular scheduled visits (cleaning, chemicals, equipment checks). Weekly or bi-weekly. Per Year.",
    descriptionAr: "زيارات منتظمة مجدولة (تنظيف، كيماويات، فحص معدات). أسبوعياً أو كل أسبوعين. سنوياً.",
    serviceCategory: "maintenance",
  },
  {
    id: "fsvc-3",
    providerId: "gulf-fountain",
    name: "Monthly Maintenance",
    nameAr: "صيانة شهرية",
    price: 30,
    priceDisplay: "30 – 60 KWD",
    priceDisplayAr: "30 – 60 د.ك",
    description: "Basic recurring cleaning and chemical balancing (standard 2 visits/week). Per Month.",
    descriptionAr: "تنظيف دوري أساسي وموازنة كيماوية (زيارتان أسبوعياً). شهرياً.",
    serviceCategory: "maintenance",
  },
  {
    id: "fsvc-4",
    providerId: "gulf-fountain",
    name: "Water Chiller Installation",
    nameAr: "تركيب مبرد مياه",
    price: 350,
    priceDisplay: "350 – 850 KWD",
    priceDisplayAr: "350 – 850 د.ك",
    description: "Cooling systems for summer use. Per Unit.",
    descriptionAr: "أنظمة تبريد للاستخدام الصيفي. لكل وحدة.",
    serviceCategory: "equipment",
  },
  {
    id: "fsvc-5",
    providerId: "gulf-fountain",
    name: "Equipment Replacement",
    nameAr: "استبدال المعدات",
    price: 15,
    priceDisplay: "15 – 90+ KWD",
    priceDisplayAr: "15 – 90+ د.ك",
    description: "Installation of pumps, motors, filters, and LED lights. Plus parts.",
    descriptionAr: "تركيب مضخات ومحركات وفلاتر وإضاءة LED. بالإضافة للقطع.",
    serviceCategory: "equipment",
  },
  {
    id: "fsvc-6",
    providerId: "gulf-fountain",
    name: "Water Features",
    nameAr: "معالم مائية",
    price: null,
    priceDisplay: "Custom Quote Only",
    priceDisplayAr: "عرض سعر مخصص فقط",
    description: "Fountains, waterfalls, jacuzzis, saunas, and steam rooms. Project-based.",
    descriptionAr: "نوافير وشلالات وجاكوزي وساونا وغرف بخار. حسب المشروع.",
    serviceCategory: "add-ons",
  },

  // Desert Springs Fountains
  {
    id: "fsvc-7",
    providerId: "desert-springs",
    name: "Fiberglass Installation",
    nameAr: "تركيب الفايبرجلاس",
    price: 3500,
    priceDisplay: "3,500 – 7,000 KWD",
    priceDisplayAr: "3,500 – 7,000 د.ك",
    description: "Installation of pre-molded fiberglass pool shells. One-time.",
    descriptionAr: "تركيب أحواض فايبرجلاس جاهزة. لمرة واحدة.",
    serviceCategory: "construction",
  },
  {
    id: "fsvc-8",
    providerId: "desert-springs",
    name: "One-time Full Cleaning",
    nameAr: "تنظيف شامل لمرة واحدة",
    price: 20,
    priceDisplay: "20 – 120 KWD",
    priceDisplayAr: "20 – 120 د.ك",
    description: "Deep cleaning (skimming, vacuuming, brushing, drains) and chemical adjustment / Acid Wash. Per Service (depends on size).",
    descriptionAr: "تنظيف عميق (كشط، شفط، فرش، تصريف) ومعالجة كيماوية / غسيل حمضي. لكل خدمة (حسب الحجم).",
    serviceCategory: "maintenance",
  },
  {
    id: "fsvc-9",
    providerId: "desert-springs",
    name: "Pool Heater Installation",
    nameAr: "تركيب سخان مسبح",
    price: 250,
    priceDisplay: "250 – 550 KWD",
    priceDisplayAr: "250 – 550 د.ك",
    description: "Heating systems for winter use. Per Unit.",
    descriptionAr: "أنظمة تدفئة للاستخدام الشتوي. لكل وحدة.",
    serviceCategory: "equipment",
  },
  {
    id: "fsvc-10",
    providerId: "desert-springs",
    name: "Repairs & Renovation",
    nameAr: "إصلاحات وتجديد",
    price: null,
    priceDisplay: "Priced per job",
    priceDisplayAr: "حسب المهمة",
    description: "Fixing leaks, cracked tiles, or blocked drains; full refurbishment. Assessment required.",
    descriptionAr: "إصلاح التسريبات والبلاط المتشقق والمصارف المسدودة؛ تجديد كامل. يتطلب تقييم.",
    serviceCategory: "repairs",
  },
  {
    id: "fsvc-11",
    providerId: "desert-springs",
    name: "Above-Ground Setup",
    nameAr: "تركيب مسبح فوق الأرض",
    price: 40,
    priceDisplay: "40 – 180 KWD",
    priceDisplayAr: "40 – 180 د.ك",
    description: "Setup of Intex or Bestway style retail pools. Per Unit.",
    descriptionAr: "تركيب مسابح Intex أو Bestway الجاهزة. لكل وحدة.",
    serviceCategory: "construction",
  },
];

// ── Fish Pool Services ────────────────────────────────────────────

const fishServices: Service[] = [
  {
    id: "fish-1",
    providerId: "kw-aquarium",
    name: "Custom Fish Pool Design & Build",
    nameAr: "تصميم وبناء حوض أسماك مخصص",
    price: 500,
    priceDisplay: "500 – 3,000+ KWD",
    priceDisplayAr: "500 – 3,000+ د.ك",
    description: "Custom indoor/outdoor fish pool design with filtration, lighting, and landscaping.",
    descriptionAr: "تصميم حوض أسماك داخلي/خارجي مخصص مع ترشيح وإضاءة وتنسيق حدائق.",
    serviceCategory: "construction",
  },
  {
    id: "fish-2",
    providerId: "kw-aquarium",
    name: "Koi Pond Installation",
    nameAr: "تركيب حوض كوي",
    price: 800,
    priceDisplay: "800 – 2,500 KWD",
    priceDisplayAr: "800 – 2,500 د.ك",
    description: "Complete koi pond setup with bio-filtration, UV sterilizer, and aeration system.",
    descriptionAr: "تركيب حوض كوي كامل مع ترشيح حيوي ومعقم أشعة فوق بنفسجية ونظام تهوية.",
    serviceCategory: "construction",
  },
  {
    id: "fish-3",
    providerId: "kw-aquarium",
    name: "Monthly Fish Pool Maintenance",
    nameAr: "صيانة شهرية لحوض الأسماك",
    price: 25,
    priceDisplay: "25 – 60 KWD",
    priceDisplayAr: "25 – 60 د.ك",
    description: "Water testing, filter cleaning, algae control, and fish health check.",
    descriptionAr: "فحص المياه، تنظيف الفلاتر، مكافحة الطحالب، وفحص صحة الأسماك.",
    serviceCategory: "maintenance",
  },
  {
    id: "fish-4",
    providerId: "kw-aquarium",
    name: "Fish & Coral Supply",
    nameAr: "توريد أسماك وشعاب مرجانية",
    price: 10,
    priceDisplay: "10 – 500+ KWD",
    priceDisplayAr: "10 – 500+ د.ك",
    description: "Live fish, coral, aquatic plants, and decorative items for your pool.",
    descriptionAr: "أسماك حية، شعاب مرجانية، نباتات مائية، وعناصر زخرفية لحوضك.",
    serviceCategory: "supplies",
  },
  {
    id: "fish-5",
    providerId: "reef-masters",
    name: "Marine Aquarium Setup",
    nameAr: "إعداد حوض بحري",
    price: 350,
    priceDisplay: "350 – 1,500 KWD",
    priceDisplayAr: "350 – 1,500 د.ك",
    description: "Complete marine/reef aquarium with live rock, protein skimmer, and LED lighting.",
    descriptionAr: "حوض بحري/شعاب مرجانية كامل مع صخور حية وكاشطة بروتين وإضاءة LED.",
    serviceCategory: "construction",
  },
  {
    id: "fish-6",
    providerId: "reef-masters",
    name: "Filtration System Upgrade",
    nameAr: "ترقية نظام الترشيح",
    price: 80,
    priceDisplay: "80 – 300 KWD",
    priceDisplayAr: "80 – 300 د.ك",
    description: "Upgrade to advanced filtration: sump, canister, or bio-filter systems.",
    descriptionAr: "ترقية إلى ترشيح متقدم: أنظمة سمب أو كانستر أو فلاتر حيوية.",
    serviceCategory: "equipment",
  },
  {
    id: "fish-7",
    providerId: "reef-masters",
    name: "Fish Pool Cleaning",
    nameAr: "تنظيف حوض الأسماك",
    price: 15,
    priceDisplay: "15 – 40 KWD",
    priceDisplayAr: "15 – 40 د.ك",
    description: "Deep cleaning, water change, substrate vacuuming, and glass scrubbing.",
    descriptionAr: "تنظيف عميق، تغيير مياه، شفط القاع، وتنظيف الزجاج.",
    serviceCategory: "maintenance",
  },
  {
    id: "fish-8",
    providerId: "reef-masters",
    name: "Fish Pool Repair",
    nameAr: "إصلاح حوض أسماك",
    price: null,
    priceDisplay: "Quote basis",
    priceDisplayAr: "بناءً على التقييم",
    description: "Leak repair, glass replacement, pump and heater fixes.",
    descriptionAr: "إصلاح التسريبات، استبدال الزجاج، إصلاح المضخات والسخانات.",
    serviceCategory: "repairs",
  },
];

export const services: Service[] = [...poolServices, ...fountainServices, ...fishServices];

// ── Helper Functions ───────────────────────────────────────────────

export function getProviderById(id: string): Provider | undefined {
  return providers.find((p) => p.id === id);
}

export function getServicesByProviderId(providerId: string): Service[] {
  return services.filter((s) => s.providerId === providerId);
}
